# name: Build and Deploy NodeJS App on AWS
# on:
#   push:
#     branches:
#     - main
  
# jobs:
#   Build-App:
#     runs-on: ubuntu-latest

#     steps:
#       - uses: actions/checkout@v4    

#       - name: Build the Docker Image
#         run: |
#          docker build . --tag 559050236729.dkr.ecr.us-east-1.amazonaws.com/dev/nodeimages:latest
         
#       - name: Configure AWS Credentials
#         uses: aws-actions/configure-aws-credentials@v2
#         with:
#           aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
#           aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#           aws-region: us-east-1 

#       - name: Login to Amazon Elastic Container Registry
#         id: login-ecr
#         uses: aws-actions/amazon-ecr-login@v1

#       - name: Push the Image to AWS ECR
#         run: |
#             docker push 559050236729.dkr.ecr.us-east-1.amazonaws.com/dev/nodeimages:latest

#       - name: Revisions on ECS with Updated Docker Images
#         uses: aws-actions/amazon-ecs-deploy-task-definition@v1
#         with:
#           task-definition: ecs-task.json
#           service: devopsmolvi-ecs-srv
#           cluster: devopsmolvi-ecs
#           wait-for-service-stability: true            


name: Build and Deploy NodeJS App to ECS Fargate

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set image tag from commit SHA
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:${{ env.IMAGE_TAG }} .
          docker tag 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:${{ env.IMAGE_TAG }} 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker image to ECR
        run: |
          docker push 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:${{ env.IMAGE_TAG }}
          docker push 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:latest

      - name: Deploy to ECS Fargate
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ecs-task.json
          service: nodeapp-task-service-d74sqlel
          cluster: frank-hippopotamus-lkyw0p
          wait-for-service-stability: true
