name: Build and Push NodeJS App to AWS ECR

on:
  push:
    branches:
      - main  # Run this workflow whenever you push to the main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      # Generate a unique tag from the commit SHA
      - name: Set image tag
        id: vars
        run: echo "IMAGE_TAG=$(echo $GITHUB_SHA | head -c7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          echo "Building Docker image..."
          docker build -t 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:${{ env.IMAGE_TAG }} .
          docker tag 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:${{ env.IMAGE_TAG }} 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:latest

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-southeast-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Push Docker images to ECR
        run: |
          echo "Pushing Docker images to ECR..."
          docker push 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:${{ env.IMAGE_TAG }}
          docker push 468907522523.dkr.ecr.ap-southeast-1.amazonaws.com/nodeapp:latest
